HumanoidCtrl:
  ros__parameters:
    InputTopicName: "/HumanoidCtrl/humanoid_msgs/msg/JointState"
    JointTopic: "/JointState"
    PublishRate: 25.0
    # RobotType: "Ti5Robot"
    # RobotType: "UnitreeG1Dof23"
    RobotType: "UnitreeG1Dof29"
    